//Testing Hunikita Kontrakan & Kostan Platform
//ini file untuk testing sudah saya sediakan
//Create a User
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Jhon Doe",
    "email": "jhondoe@gmail.com",
    "password": "12345678",
    "confPassword": "12345678",
    "role": "Pemilik Properti"

}

###
//Get All User
GET http://localhost:5000/users

###
//Get Single Data User By UUID
GET http://localhost:5000/users/6a8deb66-a8c5-457c-9528-1c07a2867dba

###
//Update User
PATCH  http://localhost:5000/users/a5e42150-be41-4832-839f-3044481d91be
Content-Type: application/json

{
    "name": "Test Kedua",
    "email": "test@gmail.com",
    "password": "",
    "confPassword": "",
    "role": "Pemilik Properti"

}

###
//Delete User 
DELETE http://localhost:5000/users/a5e42150-be41-4832-839f-3044481d91be

// TESTING USER END
###
POST http://localhost:5000/products
Content-Type: application/json
{
    "namapemilik": "Jhon Doe",
    "email": "jhondoe@gmail.com",
    "nomerhp": "08472742842",
    "namaproperti": "rukita",
    "tipeproperti": "kost",
    "alamat": "Jl. 12 Suraba",
    "jumlahkamar": "12"
    foto
}
