//Testing Hunikita Kontrakan & Kostan Platform
//ini file untuk testing sudah saya sediakan
//Create a User
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Testt",
    "email": "test@gmail.com",
    "password": "12345678",
    "confPassword": "12345678",
    "role": "Pemilik Properti"

}
###
//Get User By Id
GET http://localhost:5000/users/1
###
//Get All User
GET http://localhost:5000/users

###
GET http://localhost:5000/form
###
POST http://localhost:5000/form
Content-Type: application/json
{
  "namalengkap": "Agus",
  "email": "agus@gmail.com",
  "tentang": "Testterrr",
  "pesan": "ini contoh testing"
}